KS-5-1 math example
EgorovMS/KotlinSprint pull request #20
Opened 2024-06-25 13:54 UTC by EgorovMS

2024-06-25 20:54 UTC, ievetrovdev requested changes

2024-06-25 20:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    println("Для входа решите пример 2 + 2 = ?")
Давай будем использовать случайную генерацию чисел

2024-06-25 20:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    val mathExample = readLine()!!.toInt()
Использование оператора !! подразумевает, что ты уверен в том, что значение не может быть null. Однако, если это не так, то приложение "упадет" с ошибкой. Поэтому этот оператор считается опасным и не рекомендуется использовать. Только в крайних случаях.

2024-06-25 21:01 UTC, EgorovMS commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    val mathExample = readLine()!!.toInt()
Исходя из урока воспринял это как приемлемое написание, которое будет рассмотрено более подробно в дальнейших уроках.

2024-06-25 21:01 UTC, EgorovMS commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    println("Для входа решите пример 2 + 2 = ?")
Попробую)

2024-09-02 21:01 UTC, ievetrovdev requested changes

2024-09-02 21:01 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task1.kt
> +    val b = Random.nextInt(0, 100)
Любой импорт – лишний код в классе. Неиспользуемый импорт – неиспользуемый код. Существуют условно тонкие материи, когда надо использовать какую-то конкретную реализацию под капотом. Поэтому обоснованно может быть вызвать некую альтернативу из Котлин или похожий функционал, но с другим внутренним алгоритмом из Джавы. Ситуативно. Здесь я бы использовал экстеншн получения рандомного числа из диапазона: (1..100).random()

2024-09-03 21:12 UTC, ievetrovdev approved these changes
Отличное решение, все верно!

2024-09-04 06:52 UTC, merged