KS-5-3 guess the number
EgorovMS/KotlinSprint pull request #22
Opened 2024-09-02 19:48 UTC by EgorovMS

2024-09-02 21:09 UTC, ievetrovdev requested changes

2024-09-02 21:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    val userInputOne = readLine()?.toIntOrNull()
В данном случае лучше использовать функцию readln(), которая не будет выбрасывать исключение, если в нее прийдет null, а просто вернет строку (строка будет конфликтовать с приведением к целочисленному типу, но это другой кейс, важнее разобраться с нулябельностью)

2024-09-02 21:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    val userInputTwo = readLine()?.toIntOrNull()
В данном случае лучше использовать функцию readln(), которая не будет выбрасывать исключение, если в нее прийдет null, а просто вернет строку (строка будет конфликтовать с приведением к целочисленному типу, но это другой кейс, важнее разобраться с нулябельностью)

2024-09-02 21:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if (userInputOne == numTwo && userInputTwo == numOne) {
А если игрок ввел верные числа, но в другом порядке, порядок ввода не должен влиять на результат

2024-09-02 21:28 UTC, EgorovMS commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if (userInputOne == numTwo && userInputTwo == numOne) {
"- программа должна учитывать ввод чисел в обратном порядке."
Я воспринял это условие из задачи таким образом

2024-09-03 21:14 UTC, ievetrovdev approved these changes
Все верно, отличное решение! (можно не дописывать ?.toIntOrNull() для ввода)

2024-09-04 06:52 UTC, merged