KS-1-3 create commit
EgorovMS/KotlinSprint pull request #3
Opened 2024-06-15 15:02 UTC by EgorovMS

2024-06-16 07:39 UTC, ievetrovdev requested changes

2024-06-16 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +//    println(hour)
В условии сказано `Выведи год, час и минуту взлета по одной переменной на каждую строку;`, зачем ты комментируешь вывод?)

2024-06-16 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +    println(hour + ":" + minute)
Так как мы пишем на Котлин, лучше все таки использовать не конкатенацию (сложение), а интерполяцию)

2024-06-16 10:45 UTC, EgorovMS commented on src/main/kotlin/lesson_1/lesson1_task3.kt
> +//    println(hour)
Задание неправильно понял, подумал что в последнем выводе, должен отображаться только год и время посадки, поэтому закомментировал время взлета.

2024-06-17 09:47 UTC, ievetrovdev approved these changes

2024-06-17 16:33 UTC, merged