KS-9-4 ingredient request
EgorovMS/KotlinSprint pull request #41
Opened 2024-10-15 20:22 UTC by EgorovMS

2024-10-17 18:14 UTC, ievetrovdev requested changes

2024-10-17 18:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task4.kt
> +        println("$ingredientsList")
Предлагаю сократить код до

    println("Введите пять ингридиентов блюда через запятую:")
    val ingredients = readln().split(", ").sorted()

2024-10-17 18:51 UTC, EgorovMS commented on src/main/kotlin/lesson_9/lesson9_task4.kt
> +        println("$ingredientsList")
Я не знал, что так можно объявлять переменные

2024-10-18 20:59 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-10-19 17:56 UTC, merged