KS-2-1 average score students
EgorovMS/KotlinSprint pull request #6
Opened 2024-06-17 18:39 UTC by EgorovMS

2024-06-17 21:04 UTC, ievetrovdev requested changes

2024-06-17 21:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task1.kt
> +    println(sum / 4)
4 это магическое число, давай вынесем его в переменную

2024-06-18 19:07 UTC, EgorovMS commented on src/main/kotlin/lesson_2/lesson2_task1.kt
> +    println(sum / 4)
Да, это как то необдуманно вышло! Учитывая что во второй задаче я всё вынес в переменные и ты её принял без исправлений)

2024-06-19 19:45 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-06-19 19:50 UTC, merged