KS-2-3 translate of time
EgorovMS/KotlinSprint pull request #8
Opened 2024-06-19 18:06 UTC by EgorovMS

2024-06-19 19:43 UTC, ievetrovdev requested changes

2024-06-19 19:43 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lessons2_task3.kt
> +    println(String. format ("%d:%d", 17, 16))
Нужно вывести только рассчитанное время прибытия, в форматированном под время виде

2024-06-19 19:54 UTC, EgorovMS commented on src/main/kotlin/lesson_2/lessons2_task3.kt
> +    println(String. format ("%d:%d", 17, 16))
Как будет более корректно, удалить два лишних вывода или закоментить?

2024-06-20 08:29 UTC, EgorovMS commented
Исправил замечания, но отметил не тот файл и отправил сначала черновик для задания 2-4, как его удалить?

2024-06-20 10:49 UTC, ievetrovdev commented
> Исправил замечания, но отметил не тот файл и отправил сначала черновик для задания 2-4, как его удалить?

Переключиться на эту ветку, удалить лишний файл и закоммитить

2024-06-20 10:50 UTC, ievetrovdev requested changes

2024-06-20 10:50 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +package org.example.lesson_2
Нужно удалить

2024-06-20 21:54 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lessons2_task3.kt
> +    println(String. format ("%d:%d", 17, 16))
Всегда надо удалять, комментарии допустимы либо значимые для программы, либо если это все еще черновой вариант

2024-06-20 21:54 UTC, ievetrovdev approved these changes
Все верно! Отличное решение!

2024-06-21 06:56 UTC, merged